capp/business/routes.py
from flask import render_template, Blueprint

business=Blueprint('business',__name__)

@business.route('/business')
def business_home():
  return render_template('business.html', title='business')

capp/home/__init__.py
#

capp/home/routes.py
from flask import render_template, Blueprint

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

capp/users/routes.py
from flask import make_response, render_template, Blueprint, redirect, flash, url_for, request
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from capp import db, bcrypt
from flask_login import login_required, login_user, current_user, logout_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('¡Tu cuenta ha sido creada! ¡Ahora puedes iniciar sesión!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page = request.args.get('next')
        flash('¡Has iniciado sesión! ¡Ahora puedes empezar a utilizar nuestra aplicación Light Talk!', 'success')
        return redirect(next_page) if next_page else redirect(url_for('home.home_home'))
    else:
        flash('No se pudo iniciar sesión. ¡Verifique su correo electrónico y contraseña!', 'danger') 
  return render_template('users/login.html', title='login', form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')

    response = make_response(redirect(url_for('home.home_home')))
    response.headers['Cache-Control'] = 'no-store'
    return response

@users.route('/test-login-status')
def test_login_status():
    if current_user.is_authenticated:
        return "You are logged in!"
    else:
        return "You are logged out!"

capp/templates/business.html
{% extends "layout.html" %} {% block content %}

<!-- Header -->
<section class="section_header_business">
  <div class="container">
    <div class="header">
      <div class="box">
        <h1 style="font-size: 55px">
          <span class="text-logo"> Modelo de Negocio</span>
        </h1>
        <p style="text-align: left">
          
          El modelo de negocio de SpanishFlow se centra en la enseñanza del español coloquial mediante una plataforma interactiva gratuita, complementada con eventos culturales presenciales y virtuales. Genera ingresos a través de colaboraciones con empresas locales, integrando sus productos en el contenido educativo y eventos personalizados. Esta combinación de aprendizaje digital inmersivo y prácticas culturales ofrece una solución única para turistas, estudiantes y profesionales que buscan integrarse al entorno hispanohablante. Con un enfoque en la innovación y sostenibilidad, SpanishFlow apunta a liderar el nicho del aprendizaje práctico del idioma, destacándose frente a plataformas tradicionales.
        </p>
        <div class="container_buttons_links_header">
          <div class="btn">
            <a href="{{ url_for('static', filename='/icons/trabajo.pdf') }}"class="btn btn-primary btn-lg mr-2"style="background-color: #007bff"target="_blank">Paper</a
            >
          </div>
          <div class="btn">
            <a
              href="{{url_for('spanishflow_app.spanishflow_app_home')}}"
              class="btn btn-primary btn-lg mr-2"
              ,
              style="background-color: #007bff"
              >SpanishFLow App</a
            >
          </div>
        </div>
      </div>
      <div class="box">
        <img
          src="{{url_for('static', filename='icons/business.svg')}}"
          width="325"
          height="325"
          alt=""
        />
      </div>
    </div>
  </div>
</section>

<!-- business -->
<section class="section_body_business">
  <div class="container">
    <div class="business" style="display: block">
      <h1 style="text-align: center">Nuestro Modelo de Negocio</h1>
      <p>Nuestro modelo de negocio está orientado al español colquial:</p>
    </div>

    <!--Enumerated list (table with two columns)-->
    <div class="business">
      <div class="box_table2" style="height: 240px">
        <div class="h1 mb-3" style="text-align: center">
          <i class="fa-solid fa-briefcase"></i>
        </div>
        <h4 style="text-align: center">La Empresa</h4>
        <p class="text-left">
          El Canvas, Organigrama y Dafo de la Empresa
        </p>
        <a href="{{ url_for('static', filename='/icons/canvas.pdf') }}"class="btn btn-primary btn-lg mr-2"style="background-color: #007bff"target="_blank">Canvas y mas.</a
          > 
      </div>
      <div class="box_table2" style="height: 240px">
        <div class="h1 mb-3" style="text-align: center">
          <i class="fa-solid fa-file-powerpoint"></i>
        </div>
        <h4 style="text-align: center">Nuestra Presentación</h4>
        <p class="text-left">
          La Presentación Final de SpanishFlow.
        </p>
        <a href="{{ url_for('static', filename='/icons/slides.pdf') }}"class="btn btn-primary btn-lg mr-2"style="background-color: #007bff"target="_blank">Slides</a
          > 
      </div>
    </div>
  </div>
</div>
<br>
</section>

{% endblock content %}

capp/templates/home.html
{% extends "layout.html" %}
{% block content %}
  <!-- Header -->
  <section class="section_header_home">
  <div class="container">
    <div class="header_home">
      <div class="box">
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
        <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %} {% endif %} {% endwith %}
        <script>
          setTimeout(function () {
            var flashes = document.querySelectorAll(".alert");
            flashes.forEach((flash) => flash.remove());
          }, 5000);
        </script>
        <h1 style="font-size: 55px"><span class="text-logo"> Home</span></h1>
        <p style="text-align: left">
          La app que desarrollamos busca enseñar español informal a estudiantes, turistas y trabajadores mediante un 
          aprendizaje dinámico que simula situaciones cotidianas, enfocandose en el vocabulario y las expresiones 
          coloquiales más usadas, la app también ofrece experiencias vivenciales como eventos interactivos, talleres 
          y meetups donde los usuarios puedan practicar el idioma en contextos reales, conectando con nativos o 
          compañeros de aprendizaje. Esto fomenta no solo el conocimiento lingüístico, sino también la inmersión 
          cultural, haciendo que el aprendizaje sea más natural y efectivo.
        </p>
        {% if current_user.is_authenticated %} {% else %}
        <div class="container_buttons_links_header_home">
          <div class="btn">
            <a
              href="{{url_for('users.register')}}"
              class="btn btn-primary btn-lg mr-2"
              ,
              style="background-color: #007bff"
              >Register</a
            >
          </div>
          <div class="btn">
            <a
              href="{{url_for('users.login')}}"
              class="btn btn-primary btn-lg mr-2"
              ,
              style="background-color: #007bff"
              >Login</a
            >
          </div>
        </div>
        {% endif %}
      </div>
      <div class="box">
        <img
          src="{{url_for('static', filename='icons/home.svg')}}"
          width="325"
          height="325"
          alt=""
        />
      </div>
    </div>
  </div>
</section>

  <!-- Developers -->
  <section class="section_developers_home"> 
    <section class="section_developers">
        <div class="container">
            <div class="Our_team" style="display: block;">
                <h1>Our Team</h1>
                <p>
                  Somos un grupo multicultural con un interés en común, empreender. Juntos, combinamos nuestras diversas perspectivas y experiencias para aprender y innovar.
                </p>
            </div>
            <div class="developers">
                <div class="box1">
                    <div class="dev1">
                        <img src="{{url_for('static', filename='icons/fotos/marga.jpeg')}}" style="border-radius: 50%; width: 200px; height: 200px;">
                        <h3>Margarida Ferreirinha</h3>
                        <p>
                            Portuguesa de 22 años, Actualmente, estudio Gestión de Pequeñas y Medianas Empresas en Salamanca, enfocándome en el desarrollo de habilidades empresariales para el futuro. Entusiasta por aprender y crecer en el ámbito de los negocios.
                        </p>
                        <div class="curriculums_buttons">
                            <a class="btn_dev" href="https://www.linkedin.com/in/margarida-abreu-17a373171/" target="_blank">LinkedIn</a>
                        </div>
                    </div>
                </div>
                <div class="box1">
                        <div class="dev2">
                            <img src="{{url_for('static', filename='icons/fotos/Fede.jpg')}}" style="border-radius: 50%; width: 200px; height: 200px;">
                            <h3>Federico Cantero</h3>
                            <p>
                                Soy Paraguayo, de 22 años, que está realizando estudios en la Universidad de Salamanca sobre la Gestión de Pequeñas y Medianas Empresas para así volver mejor preparado a mi país y emprender en varios rubros.
                            </p>
                            <div class="curriculums_buttons">
                                <a class="btn_dev" href="https://www.linkedin.com/in/federico-manuel-cantero-ruiz-diaz-0706b4315/" target="_blank">LinkedIn</a>
                            </div>
                        </div>
                </div>
                <div class="box1">
                    <div class="dev3">
                        <img src="{{url_for('static', filename='icons/fotos/Santi.jpg')}}" style="border-radius: 50%; width: 200px; height: 200px;">
                        <h3>Santiago Casteñeda</h3>
                        <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
                            repellat omnis? Odit enim hic atque dolorem iste natus inventore
                            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
                            officia reiciendis ex architecto voluptates soluta ab tempore facilis
                            quisquam cum.
                        </p>
                        <div class="curriculums_buttons">
                            <a class="btn_dev" href="#" target="_blank">Curriculums</a>
                        </div>
                    </div>
            </div>
            </div>
            <div class="developers">
                <div class="box2">
                    <div class="dev4">
                        <img src="{{url_for('static', filename='icons/fotos/ana.jpeg')}}" style="border-radius: 50%; width: 200px; height: 200px;">
                        <h3>Ana Paula Amores</h3>
                        <p>
                            24 años y nacida en Ecuador, es graduada en Marketing y Publicidad. Actualmente estudia el grado en Pequeñas y Medianas Empresas (PYMES) en la Universidad de Salamanca, enfocándose en la gestión y desarrollo de proyectos empresariales.
                        </p>
                        <div class="curriculums_buttons">
                            <a class="btn_dev" href="#" target="_blank">Curriculums</a>
                        </div>
                    </div>
                </div>
                <div class="box2">
                    <div class="dev5">
                        <img src="{{url_for('static', filename='icons/fotos/era1.jpeg')}}" style="border-radius: 50%; width: 200px; height: 200px;">
                        <h3>Soracha Mary Lee</h3>
                        <p>
                            Hola, estoy de erasmus en la universidad de salamanca por el próximo curso académico. Acabo de cumplir 21 años.  Soy irlandesa y en Dublín, estudio el comercio y español.
                        </p>
                        <div class="curriculums_buttons">
                            <a class="btn_dev" href="#" target="_blank">Curriculums</a>
                        </div>
                    </div>
                </div>
                <div class="box2">
                    <div class="dev6">
                        <img src="{{url_for('static', filename='icons/fotos/era2.jpeg')}}" style="border-radius: 50%; width: 200px">
                        <h3>Anna Neary</h3>
                        <p>
                            Soy un estudiante irlandés altamente motivado que estudia Comercio Internacional en University College Dublin. Actualmente estoy en mi año Erasmus en Salamanca, España. Aquí asisto a cursos avanzados de negocios y economía en español junto a hablantes nativos, en la prestigiosa Universidad de Salamanca.
                        </p>
                        <div class="curriculums_buttons">
                            <a class="btn_dev" href="https://www.linkedin.com/in/anna-neary-681158337/" target="_blank">LinkedIn</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="developers">
                <div class="box3"></div>
                <div class="box3">
                    <div class="dev7">
                        <img src="{{url_for('static', filename='icons/fotos/era3.jpeg')}}" style="border-radius: 50%; width: 200px">
                        <h3>Aoife Temple</h3>
                        <p>
                            Soy un estudiante de Erasmus. Tengo 20 años y soy de Irlanda.  Vivo en Dublín y asisto a UCD donde estoy estudiando el grado en comercio internacional.
                        </p>
                        <div class="curriculums_buttons">
                            <a class="btn_dev" href="#" target="_blank">Curriculums</a>
                        </div>
                    </div>
                </div>
                <div class="box3"></div>
            </div>
        </div>
    </section>
</section>

{% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Font Awesome code -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!--Import the Bootstrap CSS file:-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />

    <!--For the plots-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    <!-- CSS code -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='layout.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='home.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='business.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='spanishflow_app.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='user.css') }}"
    />

    <!-- To activate media queries in devices -->
    <meta
      name="viewport"
      content="user-scalable=yes, width=device-width, initial-scale=1"
    />

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>home</title>
    {% endif %}
  </head>
  <body>
    <section class="main_navbar">
      <div class="container">
          <div class="spanishflow_navbar">
              <h1 class="logo">
                  <span class="text-logo" href="{{url_for('home.home_home')}}">
                      <i class="fa-solid fa-graduation-cap"></i>  SpanishFlow
                  </span>
              </h1>
              {% if current_user.is_authenticated %}
              <nav class="nav_bar_main">
                  <ul>
                      <li>
                          <a href="{{url_for('home.home_home')}}">Home</a>
                      </li>
                      <li>
                          <a href="{{url_for('business.business_home')}}">Business</a>
                      </li>
                      <li>
                          <a href="{{url_for('spanishflow_app.spanishflow_app_home')}}">App</a>
                      </li>
                  </ul>
              </nav>
              <nav class="nav_bar_user">
                  <ul>
                      <li>
                          <a href="{{url_for('users.logout')}}">Log Out</a>
                      </li>
                  </ul>
              </nav>
              {% else %}
              <nav class="nav_bar_main">
                  <ul>
                      <li>
                          <a href="{{url_for('home.home_home')}}">Home</a>
                      </li>
                      <li>
                          <a href="{{url_for('business.business_home')}}">Business</a>
                      </li>
                      <li>
                          <a href="{{url_for('users.login')}}">App</a>
                      </li>
                  </ul>
              </nav>
              <nav class="nav_bar_user">
                  <ul>
                      <li>
                          <a href="{{url_for('users.register')}}">Register</a>
                      </li>
                      <li>
                          <a href="{{url_for('users.login')}}">Log In</a>
                      </li>
                  </ul>
              </nav>
              {% endif %}
          </div>
      </div>
    </section>

    {% block content %} {% endblock %}

    <section class="section_footer">
      <div class="container">
        <div class="footer">
          <h1>
            <a href="#">SpanishFlow<i class="fa-solid fa-graduation-cap" style="color: #00247d"></i></a>
          </h1>
        </div>
      </div>
    </section>

    <!-- Bootstrap -->
    <!-- Question Accordion -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>